### PR TITLE
fix interoperability with Go 1.15 encoding/asn1 SET OF ordering

### LINKED ISSUE #25: issues validating signed data in go1.15
This golang commit https://github.com/golang/go/commit/f0cea848679b8f8cdc5f76e1b1e36ebb924a68f8 causes detached signatures generated by previous versions of go using this library to fail validation due to the change in ordering of [signed attributes](https://github.com/github/ietf-cms/blob/c0e5968de5ec254b2f92c770d72f27cae9c11835/verify.go#L115-L120).

Not sure of exactly the best way of fixing this, but one way would update the upstream `encoding/asn1` to allow fallback to old encoding behavior, and try both encodings, as shown below.

```
diff --git a/src/encoding/asn1/asn1.go b/src/encoding/asn1/asn1.go
index d809dde278..98df4d4ee4 100644
--- a/src/encoding/asn1/asn1.go
+++ b/src/encoding/asn1/asn1.go
@@ -805,7 +805,7 @@ func parseField(v reflect.Value, bytes []byte, initOffset int, params fieldParam
                universalTag = TagGeneralizedTime
        }
 
-       if params.set {
+       if params.set || params.setOrdered {
                universalTag = TagSet
        }
 
diff --git a/src/encoding/asn1/common.go b/src/encoding/asn1/common.go
index e2aa8bd9c5..b05fdd8b92 100644
--- a/src/encoding/asn1/common.go
+++ b/src/encoding/asn1/common.go
@@ -82,6 +82,7 @@ type fieldParameters struct {
        stringType   int    // the string tag to use when marshaling.
        timeType     int    // the time tag to use when marshaling.
        set          bool   // true iff this should be encoded as a SET
+       setOrdered   bool   // true iff this should be encoded as a sequence with a SET tag
        omitEmpty    bool   // true iff this should be omitted if empty when marshaling.
 
        // Invariants:
@@ -127,6 +128,8 @@ func parseFieldParameters(str string) (ret fieldParameters) {
                        }
                case part == "set":
                        ret.set = true
+               case part == "set_ordered":
+                       ret.setOrdered = true
                case part == "application":
                        ret.application = true
                        if ret.tag == nil {
diff --git a/src/encoding/asn1/marshal.go b/src/encoding/asn1/marshal.go
index 0d34d5aa1e..a8c05f3fb2 100644
--- a/src/encoding/asn1/marshal.go
+++ b/src/encoding/asn1/marshal.go
@@ -658,7 +658,7 @@ func makeField(v reflect.Value, params fieldParameters) (e encoder, err error) {
                }
        }
 
-       if params.set {
+       if params.set || params.setOrdered {
                if tag != TagSequence {
                        return nil, StructuralError{"non sequence tagged as set"}
                }
@@ -670,7 +670,7 @@ func makeField(v reflect.Value, params fieldParameters) (e encoder, err error) {
        // with the SET type name suffix. In this case getUniversalType returns
        // TagSet, but makeBody doesn't know about that so will treat the slice
        // as a sequence. To work around this we set params.set.
-       if tag == TagSet && !params.set {
+       if tag == TagSet && !params.set && !params.setOrdered {
                params.set = true
        }

```

```
diff --git a/go.mod b/go.mod
index c1b43ec..797e14c 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,6 @@
 module github.com/github/ietf-cms
 
-go 1.12
+go 1.15
 
 require (
        github.com/github/fakeca v0.1.0

diff --git a/protocol/protocol.go b/protocol/protocol.go
index 6a83d70..1b6b0e0 100644
--- a/protocol/protocol.go
+++ b/protocol/protocol.go
@@ -256,7 +256,33 @@ func (attrs Attributes) MarshaledForSigning() ([]byte, error) {
        seq, err := asn1.Marshal(struct {
                Attributes `asn1:"set"`
        }{attrs})
+       if err != nil {
+               return nil, err
+       }
+
+       // unwrap the outer SEQUENCE
+       var raw asn1.RawValue
+       if _, err = asn1.Unmarshal(seq, &raw); err != nil {
+               return nil, err
+       }
+
+       return raw.Bytes, nil
+}
 
+// MarshaledOrderedSetForSigning DER encodes the Attributes as needed for signing
+// SignedAttributes. Encodes as an sequence with a SET tag to comply with previous
+// golang asn1 behavior.
+//   RFC5652 explains this encoding:
+//   A separate encoding of the signedAttrs field is performed for message
+//   digest calculation. The IMPLICIT [0] tag in the signedAttrs is not used for
+//   the DER encoding, rather an EXPLICIT SET OF tag is used.  That is, the DER
+//   encoding of the EXPLICIT SET OF tag, rather than of the IMPLICIT [0] tag,
+//   MUST be included in the message digest calculation along with the length
+//   and content octets of the SignedAttributes value.
+func (attrs Attributes) MarshaledOrderedSetForSigning() ([]byte, error) {
+       seq, err := asn1.Marshal(struct {
+               Attributes `asn1:"set_ordered"`
+       }{attrs})
        if err != nil {
                return nil, err
        }
diff --git a/verify.go b/verify.go
index 3e61500..526c139 100644
--- a/verify.go
+++ b/verify.go
@@ -67,7 +67,7 @@ func (sd *SignedData) verify(econtent []byte, opts x509.VerifyOptions) ([][][]*x
        chains := make([][][]*x509.Certificate, 0, len(sd.psd.SignerInfos))
 
        for _, si := range sd.psd.SignerInfos {
-               var signedMessage []byte
+               var signedMessage, signedMessageOrdered []byte
 
                // SignedAttrs is optional if EncapContentInfo eContentType isn't id-data.
                if si.SignedAttrs == nil {
@@ -118,6 +118,10 @@ func (sd *SignedData) verify(econtent []byte, opts x509.VerifyOptions) ([][][]*x
                        if signedMessage, err = si.SignedAttrs.MarshaledForSigning(); err != nil {
                                return nil, err
                        }
+
+                       if signedMessageOrdered, err = si.SignedAttrs.MarshaledOrderedSetForSigning(); err != nil {
+                               return nil, err
+                       }
                }
 
                cert, err := si.FindCertificate(certs)
@@ -131,7 +135,13 @@ func (sd *SignedData) verify(econtent []byte, opts x509.VerifyOptions) ([][][]*x
                }
 
                if err := cert.CheckSignature(algo, signedMessage, si.Signature); err != nil {
-                       return nil, err
+                       if len(signedMessageOrdered) != 0 {
+                               if err := cert.CheckSignature(algo, signedMessageOrdered, si.Signature); err != nil {
+                                       return nil, err
+                               }
+                       } else {
+                               return nil, err
+                       }
                }
 
                // If the caller didn't specify the signature time, we'll use the verified
```

### PR DESCRIPTION
**Pull request by ddz**
X690 Section 11.6 specifies a required order for SET OFs in DER.
Go 1.15 updated `encoding/asn1` to perform this ordering, which caused
a discrepancy between the order of the attributes in `SignerInfo`
and the order in the marshaled form generated by `MarshaledForSigning()`.

The attributes are now sorted before calling `MarshaledforSigning()`
to ensure consistency. This fixes interoperability with other systems
(e.g. OpenSSL CMS) for signatures generated by `ietf-cms` when compiled
with Go >= 1.15.

In order to verify signatures created by Go < 1.15 on Go >= 1.15,
we need to preserve the received order of `SignedAttributes`. This
adds a `MarshaledForVerification()` method to `Attributes` that behaves
similarly to OpenSSL's `CMS_Attributes_Verify` template in `cms_asn1.c`.

This change also adds tests for interoperability with Go < 1.15,
Go >= 1.15, and OpenSSL CMS.

Fixes #25

### CODE REVIEW

**Comment by ddz** [comment]
This PR should also fix github/smimesign#74.

**Comment by dingelish** [comment]
Hi there, we're looking forward for the merge. Any plan on merging this? thanks!

**Review by vcsjones — APPROVED** [review]
This looks reasonable and matches my understanding of T-REC-X.690-201508 sec 11.6. Thank you for the change and the tests!

**Comment by ddz** [comment]
Thank you for the review and merge!

**Comment by PatrickHeneise** [comment]
Thanks @ddz for the fix and thanks for merging this! @vcsjones could you also create a release so I can use this in `smimesign`? I can't use go 1.14 on M1 and would like to finalize my "verified" setup. (See https://github.com/github/smimesign/issues/74)

**Comment by jalseth** [comment]
+1 This definitely warrants a patch release.

**Comment by vcsjones** [comment]
Hi y'all, we do have plans to get a release of `smimesign` out soon, stay tuned!

**Comment by pstackle** [comment]
@vcsjones Is there an update on when there can be a new release of `ietf-cms` that includes this change? It looks like the recently released `smimesign` is still depending on a broken version of `ietf-cms`.

**Pull request merged**
