### PR TITLE
Time Stamp Protocol support

### PR DESCRIPTION
**Pull request by btoews**
Some backstory on CMS:

This library is primarily concerned with CMS's `SignedData` type, which represents some data that has been signed by one or more identities. Here is a vast oversimplification of what that `SignedData` structure looks like:

```json
{
  "content": {"type": "data", "value": "Hello, world!"},
  "signers": [
    {"certificate-id": "123", "signature": "DEADBEEF"},
    {"certificate-id": "234", "signature": "DEADBEEF"}
  ],
  "certificates": [
    {"id": "123", "cert": "somecert"},
    {"id": "234", "cert": "somecert"},
    {"id": "345", "cert": "someintermediate"},
    {"id": "456", "cert": "someroot"},
  ]
}
```

[RFC3161](https://www.ietf.org/rfc/rfc3161.txt) specifies how a timestamp can be added to a `SignedData`. After adding a signature to the SignedData, you take a digest of the signature bytes and request that some timestamp authority certify that this digest existed at this time. This involves the authority creating a TimestampTokenInfo structure that looks like this (oversimplified again):

```json
{
  "message-imprint": {"hash-algo": "1.2.3.4", "hash": "<HASH-OF-SIGNATURE>"},
  "gen-time": "5/17/18 13:07:00 UTC",
}
```

Needing to be signed, this TimestampTokenInfo is then shoved into a brand new `SignedData` structure's `content` field and signed by the timestamp authority. This new `SignedData` is then shoved into the original SignedData as an attribute on the signature the timestamp is for. The end result looks something like this:

```json
{
  "content": {"type": "data", "value": "Hello, world!"},
  "signers": [{
    "certificate-id": "123",
    "signature": "<MESSAGE-SIGNATURE>",
    "timestamp": {
      "content": {
        "type": "timestamp",
        "value": {
          "message-imprint": {"hash-algo": "1.2.3.4", "hash": "<HASH-OF-MESSAGE-SIGNSATURE>"},
          "gen-time": "5/17/18 13:07:00 UTC",
        },
      },
      "signers": [
        {"certificate-id": "456", "signature": "TIMESTAMP-SIGNATURE"},
      ],
    }
  }],
}
```

This PR adds a `github.com/mastahyeti/cms/timestamp` package that implements the ASN.1 structures necessary for encoding/decoding timestamps. Timestamp support is then added to the higher-level `SignedData` type in `github.com/mastahyeti/cms`. These higher level APIs look like this:

```go
// Sign some data
signedData, _ := NewSignedData([]byte("Hello, world!"))
signedData.Sign(identity.Chain(), identity.PrivateKey)

// Get a timestamp from Digicert
signedData.AddTimestamps("http://timestamp.digicert.com")

// Print DER encoded SignedData
derEncoded, _ := signedData.ToDER()
io.Copy(os.Stdout, bytes.NewReader(derEncoded))

// For each signature in SignedData, verify signature timestamp
for _, tsv := range signedData.TimestampsVerifications() {
  _, err := tsv.Verify(identity.Certificate, identity.ChainPool())

  switch err {
  case cms.ErrNoTimestamp:
    // no timestamp on this signature
  case nil:
    // successful verification
  default:
    // failed to verify timestamp
    panic(err)
  }
}
```

You can see godocs for these new APIs [here](https://godoc.org/github.com/mastahyeti/cms-ts) and for the lower-level APIs [here](https://godoc.org/github.com/mastahyeti/cms-ts/timestamp).

### CODE REVIEW

**Comment by btoews** [comment]
@ptoomey3 I was wondering if I could get some :eyes: on this PR, mostly from an API-design perspective since you don't have much familiarity with CMS/TSP. I added a bunch of context to the OP above, but feel free to hit me up with any questions about how things work.

**Comment by btoews** [comment]
Some things I'm wondering:

Is [`func (*SignedData) TimestampsVerifications`](https://godoc.org/github.com/mastahyeti/cms-ts#SignedData.TimestampsVerifications) a reasonable way to verify timestamps for a `SignedData`? I didn't want to have a single `func (*SignedData) VerifyTimestamps() error` method, since the verification results are somewhat nuanced when you have multiple timestamped signatures in the SignedData.

Should [`func (*SignedData) Verify`](https://godoc.org/github.com/mastahyeti/cms-ts#SignedData.Verify) verify timestamps by default? Many signatures won't include timestamps, so not having one shouldn't be an error. If we encounter a signature from an expired or revoked certificate, but the signature has a valid timestamp, should we consider that signature valid and not return an error? My inclination is to not verify timestamps in this method, but to return errors for expired/revoked certificates. The caller can then look for and verify timestamps if they want.

**Comment by ptoomey3** [comment]
After looking this for a bit I think it makes sense from an API design perspective. I do agree the timestamp verification bit is where things get kinda messy. I'd assume that 99% of the time people will have only one `TimestampVerification` to check, right? Given that, the nuance of wanting to go through all of them an potentially do unique things for each one seems slightly like a "low level API". 

> since the verification results are somewhat nuanced when you have multiple timestamped signatures in the SignedData.

I'd kind of lean toward ^^ for the high level API, though it could support options ala https://golang.org/pkg/crypto/x509/#Certificate.Verify.

**Comment by btoews** [comment]
So, let's say there's a `func (*SignedData) VerifyTimestamps() error` method. What should it return if there are three signatures, each with two timestamps and verification fails for two of the timestamps? I suppose we could return a general purpose "timestamp verification failed" error?

**Comment by btoews** [comment]
Or, what should be done if there are two signatures, one of which has a valid timestamp and one of which has no timestamp?

**Comment by ptoomey3** [comment]
> So, let's say there's a func (*SignedData) VerifyTimestamps() error method. What should it return if there are three signatures, each with two timestamps and verification fails for two of the timestamps? I suppose we could return a general purpose "timestamp verification failed" error?

I don't know for sure. If we think of it like cert chain validation then you could argue that the high level API should pass so long as we find at least one valid timetstamp (at least one valid path in cert parlance). What does your gut say?

**Comment by ptoomey3** [comment]
> What should it return if there are three signatures, each with two timestamps and verification fails for two of the timestamps? 

I'd guess that for most folks they just care that at least one timestamp validates from the list of CAs they trust. So, I'd maybe vote the default behavior should be "ValidIfAny" 🤷‍♂️

**Comment by btoews** [comment]
Hmm. I hadn't thought about it this way, but the signature is derived from the content being signed and the timestamp is derived from the signature. So, it *does* make sense that a single valid/trusted timestamp is all you need.

**Comment by ptoomey3** [comment]
> So, it does make sense that a single valid/trusted timestamp is all you need.

If that isn't what they want they could either pass in a `ValidIfAll` option to `Verify` OR you expect they leverage the lower level API that lets you fetch each validation and you can verify each individually, doing whatever you want.

**Comment by btoews** [comment]
Yeah, I'd thought about introducing some kind of `VerificationPolicy` type that would let you control the behavior of verification. I'd rather punt on that though and just let people choose to use a lower-level API if they need.

**Comment by btoews** [comment]
> Hmm. I hadn't thought about it this way, but the signature is derived from the content being signed and the timestamp is derived from the signature. So, it does make sense that a single valid/trusted timestamp is all you need.

This isn't quite right, because there's no guarantee that all the signatures on a SignedData were created at or around the same time.

**Comment by btoews** [comment]
I updated this branch to be more strict when dealing with timestamps. Timestamps are now always verified when verifying a SignedData. If a signature's certificate is expired but it includes a timestamp placing the signature before the cert's expiration, the signature is considered verified. If no timestamp were present the verification would fail.

**Pull request merged**
