### PR TITLE
support verifying CMS signatures generated before go1.15 on go1.15

### PR DESCRIPTION
**Pull request by bluestealth**
Fixes parsing of CMS signatures generated in prior versions of go, on go1.15. In prior versions sets were not [sorted](https://github.com/golang/go/commit/f0cea848679b8f8cdc5f76e1b1e36ebb924a68f8) leading to the signed attributes not having the right byte ordering in the signed data. 

This pull request creates a new function `MarshaledOrderedSetForSigning` in protocol package that is used in verify to test the pre-go 1.15 byte ordering in addition to the output from `MarshaledForSigning`. It also fixes the test suite failure for go1.15.

```
[bluestealth@neptune ietf-cms]$ go version
go version go1.15.2 linux/amd64
[bluestealth@neptune ietf-cms]$ git checkout origin/main 
HEAD is now at c0e5968 v0.1.0
[bluestealth@neptune ietf-cms]$ go test -test.v -test.run TestVerifySmimesignAttachedWithTimestamp
=== RUN   TestVerifySmimesignAttachedWithTimestamp
    verify_test.go:158: crypto/rsa: verification error
--- FAIL: TestVerifySmimesignAttachedWithTimestamp (0.00s)
FAIL
exit status 1
FAIL    github.com/github/ietf-cms      0.822s
[bluestealth@neptune ietf-cms]$ git checkout origin/go1.15 
Previous HEAD position was c0e5968 v0.1.0
HEAD is now at 10f0118 support verifying CMS signatures generated before go1.15 on go1.15
[bluestealth@neptune ietf-cms]$ go test -test.v -test.run TestVerifySmimesignAttachedWithTimestamp
=== RUN   TestVerifySmimesignAttachedWithTimestamp
--- PASS: TestVerifySmimesignAttachedWithTimestamp (0.00s)
PASS
ok      github.com/github/ietf-cms      0.782s

```

### CODE REVIEW

**Comment by ddz** [comment]
This bug prevents signatures generated by `ietf-cms` (and `smimesign`) compiled with go >= 1.15 from being verified by other tools such as `gpgsm` and `openssl cms`. I am looking forward to this PR getting merged!

**Comment by oncilla** [comment]
@ddz Isn't it the other way around? I.e., signatures created by `openssl cms` fail to verify with this library.

AFAICT, this PR changes only the verification part, signature creation is kept untouched. This means that the attributes are sorted with >=1.15 according to the RFC.

TBH, I'm not sure whether the PR uses the right approach here.
I think for verification one could just always preserve the order and avoid doing two signature checks.
This also seems to be how openssl implements it, since it never complained about signatures created with <1.15.
(Note that this implies the Attributes field in SignerInfo needs to be sorted as part of the signature creation process)

I think the more nasty bit is the case where you parse a legacy signature that has unsorted attributes (e.g., created with <1.15) and then encode it again with >=1.15.
At that point, the attributes will be ordered differently in SignerInfo than what was signed in the signature. Consumers that simply preserve the order of SignerInfo will fail to verify as a result.

**Comment by bluestealth** [comment]
@Oncilla Yes, that was the main problem I was trying to solve for... signatures < 1.15 failing to verify, technically the existing code works according to the RFC afaik.

If I understand what you are saying correctly then MarshaledOrderedSetForSigning could be used for parsing all verification assuming that the original ordering is never altered in transit, like how OpenSSL implements it's parsing, and only checking that ordering.

**Comment by ddz** [comment]
@Oncilla: I actually also observed signatures generated by go > 1.4 failing to be validated by other implementations such as `openssl cms`.

I can provide more code if it helps. I am generating a NIST P-256 keypair and certs using OpenSSL but then using `cms.SignDetached` to generate the detached signature (`ietfcms-go16.txt` and `ietfcms-go14.txt` below):

```
$ cat ietfcms-go16.txt | sed 's/SIGNED MESSAGE-----/CMS-----/g' | openssl cms -verify -binary -content testdata/plaintext.txt -inform PEM -CAfile testdata/prime256v1-certificate.pem
Verification failure
140313745741120:error:2E09809E:CMS routines:CMS_SignerInfo_verify:verification failure:crypto/cms/cms_sd.c:767:

$ cat ietfcms-go14.txt | sed 's/SIGNED MESSAGE-----/CMS-----/g' | openssl cms -verify -binary -content testdata/plaintext.txt -inform PEM -CAfile testdata/prime256v1-certificate.pem
Hello World!
Verification successful
```

Upon testing this PR, I am still seeing verification failures with go 1.16 that don't occur with go 1.14. That suggests that it is a different issue causing verification by `openssl cms` to fail when using go > 1.14. I'll investigate further.

**Comment by ddz** [comment]
@Oncilla: I added a test that fails without the fix on go >= 1.15 as well as a fix that made sense to me in https://github.com/github/ietf-cms/pull/29.

**Comment by bluestealth** [comment]
@ddz Yes, that makes more sense. Also explains the behavior I was seeing. I wish I could unsee ASN1.
https://github.com/github/ietf-cms/compare/main...bluestealth:go1.15-v2?expand=1

**Comment by ddz** [comment]
@bluestealth: ASN1 has taken days from me that I will never get back... I added some more to #29 including a few of your commits as well so that it also now passes the tests related to verifying old signatures and deprecation of SHA1.

**Comment by bluestealth** [comment]
@ddz LGTM, Closing in favor of #29

**Comment by ddz** [comment]
@bluestealth: Thank you for all of your work on this PR! It was critical to helping me understand and figure out what was going on.

**Pull request closed without merging**
