### PR TITLE
Return ASN1Error with specific errors instead of ErrUnsupported

### PR DESCRIPTION
**Pull request by matthias50**
This really helps debugging why things aren't working.

### CODE REVIEW

**Review by btoews — CHANGES_REQUESTED** [review]
I think this makes the library much harder to use. By returning `ErrUnsupported`, we allow the caller to check what kind of error they are dealing with and respond appropriately. If an `ASN1Error` is returned, the caller has no easy way of differentiating this from any other error dealing with invalid ASN.1 data. Instead, maybe it would make sense to implement an `ErrUnsupported` type that can contain more information about what went wrong.

**Comment by matthias50** [comment]
> I think this makes the library much harder to use. By returning `ErrUnsupported`, we allow the caller to check what kind of error they are dealing with and respond appropriately. If an `ASN1Error` is returned, the caller has no easy way of differentiating this from any other error dealing with invalid ASN.1 data. Instead, maybe it would make sense to implement an `ErrUnsupported` type that can contain more information about what went wrong.

I put in this commit to hopefully avoid others having the same frustration I had when I was trying to figure out why the pkcs7 identity docs I was trying to verify were not working. It was frustrating when there are 8 (if I counted correctly) places in the code where this error was returned. So I ended up having to use process of elimination to figure out which one it was. This was harder than it needed to be.  

To your point of the caller not being able to figure out what is going on, I would think that the text in the error message would allow for this, so I'm not sure what I am missing here. This is actually the whole point of the PR, to give the caller some context as to why things aren't working and it would have helped me debug the problem I was having faster.

**Comment by btoews** [comment]
The issue is the calling application being able to programmatically differentiate this error from a ASN.1 error. Trying to use an algorithm that isn't supported is an entirely different class or error than trying to parse invalid CMS data.

**Comment by lgarron** [comment]
This project is now part of `smimesign`.
Please send this PR to https://github.com/github/smimesign if it's still relevant!

**Pull request closed without merging**
